### ISSUE TITLE
Gifts history

### ISSUE THREAD

**Issue by witem** [vvtomash/BirthdayManager#18]

**Comment by AAbenites** [comment]
этот мой)

**Comment by witem** [comment]
Думаю це повинна бути сторінка(поки можна навіть без пагінатора). Де буде список подарованих подарунків. З деталізацією що подарували та хто скидався.
@vvtomash Що скажеш?

**Comment by vvtomash** [comment]
Я думаю для первой итерации это может быть просто список прошедших Дней рождений с именем виновника и статусом поздравили/не поздравили, а детализацию другим ишью -  подарок и кто скидывался это нужно на отдельной странице или во всплывающем какомто хинте

**Comment by vvtomash** [comment]
А история, когда кого поздравляли, тоже нужна

**Comment by witem** [comment]
Не дуже, для цього треба групи користувачів створювати, між якими можна шарити історію. Краще потім для користувача завести історія в кому і на що він скидався, але то взагалі інше

**Comment by vvtomash** [comment]
Ок
