### ISSUE TITLE
User profile page

### ISSUE THREAD

**Issue by witem** [vvtomash/BirthdayManager#9]

**Comment by artembezruchko** [comment]
Беру

**Comment by vvtomash** [comment]
1. Имя
2. Фамилия
3. ДР 
4. Email
5. Можно обозначить простенький вишлист - будет в другом тикете делаться
6. Кнопка сохранить изменения

**Comment by vvtomash** [comment]
Все настройки в одном месте

**Comment by witem** [comment]
Вішліст це не настройки

**Comment by vvtomash** [comment]
Пофіг) хай не буде)
Треба ще "змінити пароль", решту будемо додавати потім
